version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DEVICE=cuda
    volumes:
      - ./model:/app/model
    expose:
      - "8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
